apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: evaluation-service

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - namespace.yaml
  - secretproviderclass.yaml

commonLabels:
  app: evaluation-service
  managed-by: argocd

images:
  - name: evaluation-service
    newName: 056007986659.dkr.ecr.us-east-1.amazonaws.com/fiap-fase2/evaluation-service
    newTag: 1.0.0
