apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: evaluation-service-secrets
  namespace: evaluation-service
spec:
  provider: aws
  parameters:
    region: us-east-2
    objects: |
      - objectName: "evaluation-service/SERVICE_API_KEY"
        objectType: secretsmanager
        objectAlias: SERVICE_API_KEY
      - objectName: "evaluation-service/REDIS_URL"
        objectType: secretsmanager
        objectAlias: REDIS_URL
  secretObjects:
    - secretName: evaluation-service-secrets
      type: Opaque
      data:
        - objectName: SERVICE_API_KEY
          key: SERVICE_API_KEY
        - objectName: REDIS_URL
          key: REDIS_URL
