apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  namespace: evaluation-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::570814275471:role/evaluation-service-secrets-role
