apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: analytics-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::570814275471:role/analytics-service-role
