apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: analytics-service

resources:
  - deployment.yaml
  - service.yaml
  - scaledobject.yaml
  - keda-trigger-auth.yaml
  - serviceaccount.yaml
  - namespace.yaml

commonLabels:
  app: analytics-service
  managed-by: argocd

images:
  - name: analytics-service
    newName: 056007986659.dkr.ecr.us-east-1.amazonaws.com/fiap-fase2/analytics-service
    newTag: 1.0.1
