apiVersion: v1
kind: ServiceAccount
metadata:
  name: targeting-service
  namespace: targeting-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::570814275471:role/targeting-service-secrets-role