apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Recursos de cada microserviço
resources:
  - auth-service/kustomization.yaml
  - flag-service/kustomization.yaml
  - evaluation-service/kustomization.yaml
  - targeting-service/kustomization.yaml
  - analytics-service/kustomization.yaml
