apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-service-secrets
  namespace: auth-service
spec:
  provider: aws
  parameters:
    region: us-east-2
    objects: |
      - objectName: "auth-service/DATABASE_URL"
        objectType: secretsmanager
        objectAlias: DATABASE_URL
      - objectName: "auth-service/MASTER_KEY"
        objectType: secretsmanager
        objectAlias: MASTER_KEY
  secretObjects:
    - secretName: auth-service-secrets
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: MASTER_KEY
          key: MASTER_KEY