apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: targeting-service-secrets
  namespace: targeting-service
spec:
  provider: aws
  parameters:
    region: us-east-2
    objects: |
      - objectName: "targeting-service/DATABASE_URL"
        objectType: secretsmanager
        objectAlias: DATABASE_URL
  secretObjects:
    - secretName: targeting-service-secrets
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL